MOCK_JOBS = [
    {
        "_id": "1",
        "title": "Backend Python Developer",
        "company": "Google",
        "description": "Remote job building APIs",
        "tags": ["python", "cloud"],
        "location": "Remote",
        "job_type": "full time",
        "salary": "100000",
        "date_posted": "2025-07-01",
        "link": "https://google.com/jobs/1",
        "contact": "jobs@google.com",
        "job_hash": "hash1",
        "source": "telegram",
        "fetched_at": "2025-07-01T12:00:00Z"
    },
    {
        "_id": "2",
        "title": "Frontend React Engineer",
        "company": "Meta",
        "description": "Frontend with React, Next.js",
        "tags": ["react", "frontend"],
        "location": "Bangalore",
        "job_type": "part time",
        "salary": "30000",
        "date_posted": "2025-06-25",
        "link": "https://meta.com/jobs/2",
        "contact": "jobs@meta.com",
        "job_hash": "hash2",
        "source": "telegram",
        "fetched_at": "2025-06-25T12:00:00Z"
    },
    {
        "_id": "3",
        "title": "Cloud Data Scientist",
        "company": "Amazon",
        "description": "AWS, ML, Python",
        "tags": ["python", "ml", "cloud"],
        "location": "Remote",
        "job_type": "contract",
        "salary": "150000",
        "date_posted": "2025-07-05",
        "link": "https://amazon.com/jobs/3",
        "contact": "jobs@amazon.com",
        "job_hash": "hash3",
        "source": "telegram",
        "fetched_at": "2025-07-05T12:00:00Z"
    },
    {
        "_id": "4",
        "title": "Crypto Analyst",
        "company": "Binance",
        "description": "Blockchain, Crypto, Python",
        "tags": ["crypto", "python"],
        "location": "Singapore",
        "job_type": "full time",
        "salary": "85000",
        "date_posted": "2025-07-08",
        "link": "https://binance.com/jobs/4",
        "contact": "jobs@binance.com",
        "job_hash": "hash4",
        "source": "telegram",
        "fetched_at": "2025-07-08T12:00:00Z"
    }
]
